name: Unit tests

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ actions-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Install grails 1.3.9
      uses: sdkman/sdkman-action@master
      id: sdkman
      with:
        candidate: grails
        version: 1.3.9
    - name: Unzip grails
      shell: bash
      run: unzip  ${{ steps.sdkman.outputs.file }} -d $HOME/
    - name: List files
      shell: bash
      run: ls $HOME/grails-1.3.9 -al
#     - name: npm install
#       run: npm install
#     - name: npm run bundle
#       run: npm run bundle
    - name: grails test-app :unit
      run: '$HOME/grails-1.3.9/grails test-app unit: --non-interactive -echoOut -echoErr'
#     - name: npm test
#       run: npm test
