# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Unit tests

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ actions-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: curl sdkman
      run: curl -s http://get.sdkman.io | bash
    - name: echo sdkman
      run: echo sdkman_auto_answer=true > ~/.sdkman/etc/config
    - name: source sdkman
      run: source "~/.sdkman/bin/sdkman-init.sh"
    - name: install grails
      run: sdk install grails 1.3.9
    - name: npm install
      run: npm install
    - name: npm run bundle
      run: npm run bundle
    - name: grails test-app :unit
      run: 'grails test-app unit: --non-interactive -echoOut -echoErr'
